### ISSUE TITLE
How to specify OPENAI_API_BASE

### ISSUE THREAD

**Issue by lem0ke** [vivekuppal/transcribe#151] opened 2024-02-18 17:10 UTC
Now in override I can only customize the key, but it is more difficult to use the OpenAI service directly in my country, I hope it is possible to specify OPENAI_API_BASE. if it is possible please let me know the temporary solution to specify OPENAI_API_BASE, I really need it now. Thank you 🙏🙏🙏

**Comment by mang0sw33t** [comment] 2024-02-18 18:59
OPENAI_API_BASE can be made configurable.

See this example where we are setting the base url to a different value
https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/examples/together/stt.py#L8

To configure it the following places in code need to be changed similar to above.
https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L141
https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L231
https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L251

https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/sdk/transcriber_models.py#L194

Please submit a PR with the change and I can help with making all the changes.

**Comment by lem0ke** [comment] 2024-02-19 04:51
> OPENAI_API_BASE can be made configurable.OPENAI_API_BASE 可以进行配置。
> 
> See this example where we are setting the base url to a different value请参阅此示例，我们将基础 url 设置为不同的值
> 
> https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/examples/together/stt.py#L8
> 
> To configure it the following places in code need to be changed similar to above.要对其进行配置，需要对代码中的以下位置进行类似修改。
> 
> https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L141
> 
> https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L231
> 
> https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/app/transcribe/gpt_responder.py#L251
> 
> https://github.com/vivekuppal/transcribe/blob/e30827845e74ae7c5cdb51787fdd4265310ab9c8/sdk/transcriber_models.py#L194
> 
> Please submit a PR with the change and I can help with making all the changes.请提交一份修改 PR，我可以帮助您完成所有修改。

I have submitted some of the changes, thank you for your help! 🙏

**Comment by mang0sw33t** [comment] 2024-02-19 18:32
Resolved in #152.

When using OpenAI based services but need to use a different base_url than 'https://api.openai.com/v1'
In override.yaml add the following

```
OpenAI:
  api_key: 'API_KEY'
  base_url: 'BASE_URL_FOR_API'
```

Let us know if this resolves the issue for you.

**Comment by lem0ke** [comment] 2024-02-20 05:43
> Resolved in #152.
> 
> When using OpenAI based services but need to use a different base_url than 'https://api.openai.com/v1' In override.yaml add the following
> 
> ```
> OpenAI:
>   api_key: 'API_KEY'
>   base_url: 'BASE_URL_FOR_API'
> ```
> 
> Let us know if this resolves the issue for you.

I have tried several times but have not succeeded in compiling the program, there are always numerous problems that lead to compilation errors. Can I ask you again to generate an installation file of the latest version for me? I'm really sorry to bother you again.

**Comment by lem0ke** [comment] 2024-02-22 13:20
> Resolved in #152. 已在 #152 中解决。
> 
> When using OpenAI based services but need to use a different base_url than 'https://api.openai.com/v1'当使用基于 OpenAI 的服务，但需要使用不同于 ' https://api.openai.com/v1' 的 base_url 时 In override.yaml add the following在 override.yaml 中添加以下内容
> 
> ```
> OpenAI:
>   api_key: 'API_KEY'
>   base_url: 'BASE_URL_FOR_API'
> ```
> 
> Let us know if this resolves the issue for you.如果问题得到解决，请告诉我们。

My friend told me that I can follow another part of the command in the readme to run the program directly instead of running it through the compiled exe program, but after my attempts, I had problems twice while installing the environment according to the tutorials, and once again I ask for your help in updating the compiled program, and that one I should be able to run perfectly.If I could solve the problem myself, I really wouldn't bother you again.
![PixPin_2024-02-22_21-09-43](https://github.com/vivekuppal/transcribe/assets/76465380/2a1f7128-66e5-4926-a3b0-097f758734ec)
![PixPin_2024-02-22_21-14-01](https://github.com/vivekuppal/transcribe/assets/76465380/96d87b05-19f2-4a34-99f4-a8dfa45854b7)

**Comment by lem0ke** [comment] 2024-02-24 09:28
> Resolved in #152. 已在 #152 中解决。
> 
> When using OpenAI based services but need to use a different base_url than 'https://api.openai.com/v1'当使用基于 OpenAI 的服务，但需要使用不同于 ' https://api.openai.com/v1' 的 base_url 时 In override.yaml add the following在 override.yaml 中添加以下内容
> 
> ```
> OpenAI:
>   api_key: 'API_KEY'
>   base_url: 'BASE_URL_FOR_API'
> ```
> 
> Let us know if this resolves the issue for you.如果问题得到解决，请告诉我们。

After many attempts, I managed to run the program, but it doesn't work. I have confirmed that the tts service provided by the api_base site that I have filled out works without issue. Talking to the webmaster of the api_base site I filled in, I learned that he thinks it is an ssl issue.
![PixPin_2024-02-24_17-28-16](https://github.com/vivekuppal/transcribe/assets/76465380/e356318a-c3a3-4ff2-af11-94e57e3d4905)

**Comment by mang0sw33t** [comment] 2024-02-26 16:40
Share the api_base site and we can attempt to validate
or
We can debug it in a live session, provide a video conference link
or
Share an email and we will invite you to join the community chat where we can discuss further

**Comment by lem0ke** [comment] 2024-03-01 08:55
> @lem0ke eggi and em ok ?
> 
> tts -> Text To Speech -> Transcribe doesn't use it from OpenAI. No relevance ???
> 
> what the ssl error you getting what the api_base site url?

He told me later that he was drunk that day and misread it, not an ssl issue. But mine still doesn't work.
![PixPin_2024-03-01_16-54-20](https://github.com/vivekuppal/transcribe/assets/76465380/6b94300c-681c-4392-82f5-2da5db507919)

**Comment by lem0ke** [comment] 2024-03-01 08:57
> Share the api_base site and we can attempt to validate or We can debug it in a live session, provide a video conference link or Share an email and we will invite you to join the community chat where we can discuss further

My e-mail is : humblejokes@outlook.com

**Comment by mang0sw33t** [comment] 2024-03-01 19:45
Invite sent to above email.
We are improving the code base to handle this case better in #157 so diagnosing the problem is easier.
The underlying problem seems to be with the provider.

You are using the `--api` option.
Speech to text is being done using the OpenAI provider service. The API call is timing out. I believe the default timeout is 30 seconds.

One thing you can try is to use the following

`python main.py`
instead of
`python main.py --api`

Expected behavior in this case is Speech to text will work ok.
Let us know how it goes.

**Comment by mang0sw33t** [comment] 2024-03-02 17:28
Let us know if this resolved the issue 
and 
if you still require to generate binaries. It will take a couple of days at least to generate the binaries.

**Closed** 2024-03-08 15:08 UTC
Labels: environmental
