### ISSUE TITLE
Responses are taking more than 10 seconds  and also not able to clear Speaker Input

### ISSUE THREAD

**Issue by sdhreddy** [vivekuppal/transcribe#63] opened 2023-09-08 14:42 UTC
Each response is taking around 10 seconds, maybe because I am not able to clear the Speaker Input when I press clear audio transcript.

**Comment by vivekuppal** [comment] 2023-09-08 15:22
I can confirm that Speaker responses are not being cleared from the UI. This will be fixed in the next 24 hours.
I did measurements for a 10 minute conversation to get responses on demand by pressing the button in UI.
The UI update time in these cases varied between 1-2s with the worst case being 2.5s

```
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.144041
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.440220
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.239127
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.815653
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.450237
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.002325
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.847213
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.560924
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.149956
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.276162
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.913741
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.081488
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.721070
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.936763
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.015842
Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.360652
```

Local processing in all cases is under 10ms. 
Nearly all the time is in waiting for response from LLM.
The behavior in the continuous case is the same as well. It is not noticeable though because LLM is pinged in the background and the user does not know how long it takes for LLM to respond. 

Could you provide some more context into how long the conversation is, may be share the transcript of the conversation by saving to file. I can attempt to recreate the issue.

**Comment by vivekuppal** [comment] 2023-09-08 15:53
The issue of clearing Speaker Input when using the clear audio transcript menu item has been resolved. 
Please pull the latest.

**Comment by sdhreddy** [comment] 2023-09-08 16:58
> I can confirm that Speaker responses are not being cleared from the UI. This will be fixed in the next 24 hours. I did measurements for a 10 minute conversation to get responses on demand by pressing the button in UI. The UI update time in these cases varied between 1-2s with the worst case being 2.5s
> 
> ```
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.144041
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.440220
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.239127
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.815653
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.450237
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.002325
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.847213
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.560924
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.149956
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.276162
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.913741
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.081488
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.721070
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:01.936763
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.015842
> Duration(dd:hh:ss:ms) of update_response_ui_now 0:00:02.360652
> ```
> 
> Local processing in all cases is under 10ms. Nearly all the time is in waiting for response from LLM. The behavior in the continuous case is the same as well. It is not noticeable though because LLM is pinged in the background and the user does not know how long it takes for LLM to respond.
> 
> Could you provide some more context into how long the conversation is, may be share the transcript of the conversation by saving to file. I can attempt to recreate the issue.

The response time seems to be bit faster if i use Continues Response option, however its still around 5 seconds after speaking the input.  i am asking simple questions.  Not sure if its because I couldn't clear the history of input.  Now that it has been fixed, will try clearing before each question and see if response time changes.  Also, does  using different models  help or hurt with response times? I tried with tiny, base and small , all are responding slowly.

**Comment by sdhreddy** [comment] 2023-09-08 17:05
I can confirm now, that after clearing Speaker Input, it response time improved drastically , average is 1 second.  If not, its taking longer.

**Comment by vivekuppal** [comment] 2023-09-08 18:37
I am going with the assumption that the context of this discussion is `Suggest Response Now` button. 
When a user clicks the `Suggest Response Now` button it is taking a long time in your case to get an answer for the question from chatGPT (LLM).
Please confirm my assumption.

There are 2 aspects I believe
1. Speech to text - Once the user speaks into the microphone, how long does it take for the text to appear in Transcribe
    This depends on the model (tiny, base, small) and processing power of the machine where Transcribe is being executed.
    There is always a possibility of a defect slowing down the mic speech to text functionality.

2. Response from chatGPT (LLM) - Once the user clicks the `Suggest Response Now` button, how long does it take get a response from LLM
    This depends on the response time of openAI APIs

Could you please elaborate which of the above two scenario are you seeing a delay in.

**Comment by sdhreddy** [comment] 2023-09-08 18:48
Your assumption is correct.  I am referring to number 2. Response from chatGPT.  If i click Respond now, its taking long time.  If i do continuously, its faster.   Also , clearing the speaker input before each question is providing faster responses.

**Comment by vivekuppal** [comment] 2023-09-08 19:45
One thing that might be helpful, in the file `AudioRecorder.py`, there is a constant `RECORD_TIMEOUT` it is set to 3 (seconds). It is the length of speech we attempt to transcribe at a time. 
You can set it to 1 (second). That will improve the response time of Speech to Text part.

Feedback from your usage would be valuable to figure if we should make it configurable in some way.

**Comment by vivekuppal** [comment] 2023-09-09 20:54
Resolving based on the conversation thus far. 
In case there are further questions, please re-open.

**Closed by vivekuppal** 2023-09-09 20:54 UTC
Labels: bug

**Comment by sdhreddy** [comment] 2023-09-26 17:44
hey with the latest changes, i dont see RECORD_TIMEOUT in AudioRecorder.py? How would i set the time for it to hear my voice before transcribing? Right now its transcribing every second and its only capturing incomplete sentences/queries?

**Comment by vivekuppal** [comment] 2023-10-03 01:35
In `parameters.yaml` file in `General` section there is a parameter `transcript_audio_duration_seconds`.
It serves the same purpose as RECORD_TIMEOUT.
The purpose of doing this was to ensure that users do not have to change code to alter some configuration settings.
If you use an alternate value for RECORD_TIMEOUT that would be great to know.

**Comment by sdhreddy** [comment] 2023-10-03 05:26
Thanks, for me transcript_audio_duration_seconds = 4 seconds helps drastically to capture the audio input from speaker. I have changed it in yaml file and it works perfectly without ever missing the input.
