### ISSUE TITLE
Option to edit speaker text

### ISSUE THREAD

**Issue by pramodvasireddy** [vivekuppal/transcribe#181] opened 2024-03-20 19:54 UTC
I felt like if there is an option to edit the text what the speaker said would be a good feature. sometimes it is unable to transcribe some words properly. 

I also think not only listening to the speaker, there should be a choice to type and get a response.

**Comment by tan-banana** [comment] 2024-03-21 20:31
use can change the whisper models or use the speaker diarization to solve this. the llm will respond even if only half the question is transcribed if your context and stuff it setup ahead and debugged and the model is smart enough.  A better way would be to add context verbally live. the issue is when you try to do this it only works half the time. like you: "so my experinece in 3 minutes hmm let me think" and then you could reprompt the llm that way. more reprompt needs are caused by the hallucinations that mess up the context weighting.

**Comment by tan-banana** [comment] 2024-04-04 16:42
I noticed its possibel to edit the text and then right click over it and get a repsonse but its not persistant

**Comment by mang0sw33t** [comment] 2024-04-05 14:32
> I noticed its possibel to edit the text and then right click over it and get a repsonse but its not persistant

I did not see how to do it.
Can you elaborate how?

**Comment by tan-banana** [comment] 2024-04-05 17:23
STEPS: 
1.  type into the left hand of the ui. 
2. highlight that text and whatever else you want to include thats nearby 
3. right click and select generate text 
4. the llm returns the answer to that selected text doesnt matter whether or not it was transcribed since in this case it was typed by the user into the llm. 
5. the text disappears that was typed by the user.

> > I noticed its possibel to edit the text and then right click over it and get a repsonse but its not persistant
> 
> I did not see how to do it. Can you elaborate how?

**Comment by vivekuppal** [comment] 2024-05-30 22:28
Addressed in PR #226

**Closed** 2024-05-30 22:30 UTC
Labels: enhancement
